### ISSUE TITLE
All observations are in the same group?? Please help!!

### ISSUE THREAD

**Issue by slvrshot** [twbattaglia/koeken#2]
I'm trying to run your script but I get an error. I assume it has something to do with my mapping file but I am not sure how I need to fix it.

Also I don't really have time points in my data. All I want to see is there a differential abundance of OTUs between sites. My group significance data from QIIME suggest there is but I'd like to see this visualized in Lefse. Please help!!! Thanks. 

/macqiime/anaconda/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in kruskal.test.default(c(0, 25.0400641025915, 0, 0, 0, 0, 0, 0,  : 
  all observations are in the same group

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/macqiime/anaconda/bin/run_lefse.py", line 67, in <module>
    kw_ok,pv = test_kw_r(cls,feat_values,params['anova_alpha'],sorted(cls.keys()))
  File "/macqiime/anaconda/bin/lefse.py", line 59, in test_kw_r
    kw_res = robjects.r('kruskal.test('+fo+',)$p.value')
  File "/macqiime/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 362, in __call__
    res = self.eval(p)
  File "/macqiime/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/macqiime/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in kruskal.test.default(c(0, 25.0400641025915, 0, 0, 0, 0, 0, 0,  : 
  all observations are in the same group

Traceback (most recent call last):
  File "/macqiime/anaconda/bin/plot_cladogram.py", line 345, in <module>
    clad_tree = read_data(params['input_file'],params)	
  File "/macqiime/anaconda/bin/plot_cladogram.py", line 105, in read_data
    with open(input_file, 'r') as inp:
IOError: [Errno 2] No such file or directory: 'test//lefse_output/run_lefse/Third.txt'
[map_gut_final6.txt](https://github.com/twbattaglia/koeken/files/740817/map_gut_final6.txt)

**Comment by twbattaglia** [comment]
Hey @slvrshot, can you please attach the text file located in the **summarize_taxa/** folder and list the command you used?

Thanks,

**Comment by slvrshot** [comment]
[map_gut_final6_L6.txt](https://github.com/twbattaglia/koeken/files/740874/map_gut_final6_L6.txt)

koeken.py -i gut_15000_json.biom -m map_gut_final6.txt -cl Site -o test/ -sp Time -pc
[gut_15000_json.biom.zip](https://github.com/twbattaglia/koeken/files/740877/gut_15000_json.biom.zip)


I've uploaded the output from summarize_taxa.py: map_gut_final6_L6.txt
I've also included the original uncollapsed .biom file

Thanks!!!

**Comment by twbattaglia** [comment]
Hey @slvrshot, so it looks like you are getting this error because each time the program splits the table by "**Time**", there is only one class of "**Sites**" in the table. 

But if I understand correctly, you would like to just see if there is a difference between all 4 "Sites"?  In that case you can bypass the splitting part of the program by adding a new column in your mapping file that has the same value for each sample ( [map_gut_final6_fixed.txt](https://github.com/twbattaglia/koeken/files/742265/map_gut_final6_fixed.txt) ) and then select that column name as your **--split** variable.  This will cause the program to include all the samples in the comparison because each sample has the same level.

So the full command would be:
````shell
koeken.py -i gut_15000_json.biom -o test/ -m map_gut_final6_fixed.txt --split Level -cl Site -pc
````

In the near future, I'm going to be updating the program dramatically and adding options like these to skip the split and just do a simple single comparison.

Hope this helps!

**Comment by slvrshot** [comment]
Thanks!!!!

**Comment by orlaskill** [comment]
Hi all, 

I am also experiencing this same issue. I cant understand what formatting error I am doing wrong. 
Would it be possible for you to help? I am very new to LEfSe, so my apologies if it is a very minor/obvious fix! 

thanks in advance!


[Lefse_ASV_PIGLETS.txt](https://github.com/twbattaglia/koeken/files/9211222/Lefse_ASV_PIGLETS.txt)
